theme: jekyll-theme-minimal

title: "IFIP 2.9"

description: >- # this means to ignore newlines until "baseurl:"
  Software Requirements Engineering was established in 1993. It is a 
  working group within TC-2 (Software: Theory and Practice), which in 
  turn is a technical committee of IFIP (International Federation for 
  Information Processing)

logo: "/assets/images/logo.png"